### ISSUE TITLE
Não usar o yml.load

### ISSUE THREAD

**Issue by mbodock** [lramosduarte/rcis#1]
O pyyaml não recomenda usar o `load`:

> Warning: It is not safe to call yaml.load with any data received from an untrusted source! yaml.load is as powerful as pickle.load and so may call any Python function. Check the yaml.safe_load function though

Source: https://pyyaml.org/wiki/PyYAMLDocumentation

**Comment by lramosduarte** [comment]
Nesse contexto não teria problema, mas vou trocar.
